/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package postgres_data_collection_configuration.can_activity;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Value extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4071123448428898088L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"postgres_data_collection_configuration.can_activity\",\"fields\":[{\"name\":\"legacy_device_serial_number\",\"type\":\"string\"},{\"name\":\"asset_id\",\"type\":{\"type\":\"string\",\"connect.version\":1,\"connect.name\":\"io.debezium.data.Uuid\"}},{\"name\":\"can_activity_state\",\"type\":{\"type\":\"string\",\"connect.default\":\"NO_ACTIVITY_DETECTED\"},\"default\":\"NO_ACTIVITY_DETECTED\"},{\"name\":\"can_instance\",\"type\":{\"type\":\"string\",\"connect.default\":\"CAN_1\"},\"default\":\"CAN_1\"},{\"name\":\"created_at\",\"type\":{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"io.debezium.time.MicroTimestamp\"}},{\"name\":\"last_modified_at\",\"type\":[\"null\",{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"io.debezium.time.MicroTimestamp\"}],\"default\":null}],\"connect.name\":\"postgres_data_collection_configuration.can_activity.Value\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Value> ENCODER =
      new BinaryMessageEncoder<Value>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Value> DECODER =
      new BinaryMessageDecoder<Value>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Value> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Value> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Value> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Value>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Value to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Value from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Value instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Value fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence legacy_device_serial_number;
  @Deprecated public java.lang.CharSequence asset_id;
  @Deprecated public java.lang.CharSequence can_activity_state;
  @Deprecated public java.lang.CharSequence can_instance;
  @Deprecated public long created_at;
  @Deprecated public java.lang.Long last_modified_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Value() {}

  /**
   * All-args constructor.
   * @param legacy_device_serial_number The new value for legacy_device_serial_number
   * @param asset_id The new value for asset_id
   * @param can_activity_state The new value for can_activity_state
   * @param can_instance The new value for can_instance
   * @param created_at The new value for created_at
   * @param last_modified_at The new value for last_modified_at
   */
  public Value(java.lang.CharSequence legacy_device_serial_number, java.lang.CharSequence asset_id, java.lang.CharSequence can_activity_state, java.lang.CharSequence can_instance, java.lang.Long created_at, java.lang.Long last_modified_at) {
    this.legacy_device_serial_number = legacy_device_serial_number;
    this.asset_id = asset_id;
    this.can_activity_state = can_activity_state;
    this.can_instance = can_instance;
    this.created_at = created_at;
    this.last_modified_at = last_modified_at;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return legacy_device_serial_number;
    case 1: return asset_id;
    case 2: return can_activity_state;
    case 3: return can_instance;
    case 4: return created_at;
    case 5: return last_modified_at;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: legacy_device_serial_number = (java.lang.CharSequence)value$; break;
    case 1: asset_id = (java.lang.CharSequence)value$; break;
    case 2: can_activity_state = (java.lang.CharSequence)value$; break;
    case 3: can_instance = (java.lang.CharSequence)value$; break;
    case 4: created_at = (java.lang.Long)value$; break;
    case 5: last_modified_at = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'legacy_device_serial_number' field.
   * @return The value of the 'legacy_device_serial_number' field.
   */
  public java.lang.CharSequence getLegacyDeviceSerialNumber() {
    return legacy_device_serial_number;
  }


  /**
   * Sets the value of the 'legacy_device_serial_number' field.
   * @param value the value to set.
   */
  public void setLegacyDeviceSerialNumber(java.lang.CharSequence value) {
    this.legacy_device_serial_number = value;
  }

  /**
   * Gets the value of the 'asset_id' field.
   * @return The value of the 'asset_id' field.
   */
  public java.lang.CharSequence getAssetId() {
    return asset_id;
  }


  /**
   * Sets the value of the 'asset_id' field.
   * @param value the value to set.
   */
  public void setAssetId(java.lang.CharSequence value) {
    this.asset_id = value;
  }

  /**
   * Gets the value of the 'can_activity_state' field.
   * @return The value of the 'can_activity_state' field.
   */
  public java.lang.CharSequence getCanActivityState() {
    return can_activity_state;
  }


  /**
   * Sets the value of the 'can_activity_state' field.
   * @param value the value to set.
   */
  public void setCanActivityState(java.lang.CharSequence value) {
    this.can_activity_state = value;
  }

  /**
   * Gets the value of the 'can_instance' field.
   * @return The value of the 'can_instance' field.
   */
  public java.lang.CharSequence getCanInstance() {
    return can_instance;
  }


  /**
   * Sets the value of the 'can_instance' field.
   * @param value the value to set.
   */
  public void setCanInstance(java.lang.CharSequence value) {
    this.can_instance = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public long getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.created_at = value;
  }

  /**
   * Gets the value of the 'last_modified_at' field.
   * @return The value of the 'last_modified_at' field.
   */
  public java.lang.Long getLastModifiedAt() {
    return last_modified_at;
  }


  /**
   * Sets the value of the 'last_modified_at' field.
   * @param value the value to set.
   */
  public void setLastModifiedAt(java.lang.Long value) {
    this.last_modified_at = value;
  }

  /**
   * Creates a new Value RecordBuilder.
   * @return A new Value RecordBuilder
   */
  public static postgres_data_collection_configuration.can_activity.Value.Builder newBuilder() {
    return new postgres_data_collection_configuration.can_activity.Value.Builder();
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Value RecordBuilder
   */
  public static postgres_data_collection_configuration.can_activity.Value.Builder newBuilder(postgres_data_collection_configuration.can_activity.Value.Builder other) {
    if (other == null) {
      return new postgres_data_collection_configuration.can_activity.Value.Builder();
    } else {
      return new postgres_data_collection_configuration.can_activity.Value.Builder(other);
    }
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Value instance.
   * @param other The existing instance to copy.
   * @return A new Value RecordBuilder
   */
  public static postgres_data_collection_configuration.can_activity.Value.Builder newBuilder(postgres_data_collection_configuration.can_activity.Value other) {
    if (other == null) {
      return new postgres_data_collection_configuration.can_activity.Value.Builder();
    } else {
      return new postgres_data_collection_configuration.can_activity.Value.Builder(other);
    }
  }

  /**
   * RecordBuilder for Value instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Value>
    implements org.apache.avro.data.RecordBuilder<Value> {

    private java.lang.CharSequence legacy_device_serial_number;
    private java.lang.CharSequence asset_id;
    private java.lang.CharSequence can_activity_state;
    private java.lang.CharSequence can_instance;
    private long created_at;
    private java.lang.Long last_modified_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(postgres_data_collection_configuration.can_activity.Value.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.legacy_device_serial_number)) {
        this.legacy_device_serial_number = data().deepCopy(fields()[0].schema(), other.legacy_device_serial_number);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.asset_id)) {
        this.asset_id = data().deepCopy(fields()[1].schema(), other.asset_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.can_activity_state)) {
        this.can_activity_state = data().deepCopy(fields()[2].schema(), other.can_activity_state);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.can_instance)) {
        this.can_instance = data().deepCopy(fields()[3].schema(), other.can_instance);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.created_at)) {
        this.created_at = data().deepCopy(fields()[4].schema(), other.created_at);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.last_modified_at)) {
        this.last_modified_at = data().deepCopy(fields()[5].schema(), other.last_modified_at);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Value instance
     * @param other The existing instance to copy.
     */
    private Builder(postgres_data_collection_configuration.can_activity.Value other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.legacy_device_serial_number)) {
        this.legacy_device_serial_number = data().deepCopy(fields()[0].schema(), other.legacy_device_serial_number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.asset_id)) {
        this.asset_id = data().deepCopy(fields()[1].schema(), other.asset_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.can_activity_state)) {
        this.can_activity_state = data().deepCopy(fields()[2].schema(), other.can_activity_state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.can_instance)) {
        this.can_instance = data().deepCopy(fields()[3].schema(), other.can_instance);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.created_at)) {
        this.created_at = data().deepCopy(fields()[4].schema(), other.created_at);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.last_modified_at)) {
        this.last_modified_at = data().deepCopy(fields()[5].schema(), other.last_modified_at);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'legacy_device_serial_number' field.
      * @return The value.
      */
    public java.lang.CharSequence getLegacyDeviceSerialNumber() {
      return legacy_device_serial_number;
    }


    /**
      * Sets the value of the 'legacy_device_serial_number' field.
      * @param value The value of 'legacy_device_serial_number'.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder setLegacyDeviceSerialNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.legacy_device_serial_number = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'legacy_device_serial_number' field has been set.
      * @return True if the 'legacy_device_serial_number' field has been set, false otherwise.
      */
    public boolean hasLegacyDeviceSerialNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'legacy_device_serial_number' field.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder clearLegacyDeviceSerialNumber() {
      legacy_device_serial_number = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'asset_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getAssetId() {
      return asset_id;
    }


    /**
      * Sets the value of the 'asset_id' field.
      * @param value The value of 'asset_id'.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder setAssetId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.asset_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'asset_id' field has been set.
      * @return True if the 'asset_id' field has been set, false otherwise.
      */
    public boolean hasAssetId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'asset_id' field.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder clearAssetId() {
      asset_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'can_activity_state' field.
      * @return The value.
      */
    public java.lang.CharSequence getCanActivityState() {
      return can_activity_state;
    }


    /**
      * Sets the value of the 'can_activity_state' field.
      * @param value The value of 'can_activity_state'.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder setCanActivityState(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.can_activity_state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'can_activity_state' field has been set.
      * @return True if the 'can_activity_state' field has been set, false otherwise.
      */
    public boolean hasCanActivityState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'can_activity_state' field.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder clearCanActivityState() {
      can_activity_state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'can_instance' field.
      * @return The value.
      */
    public java.lang.CharSequence getCanInstance() {
      return can_instance;
    }


    /**
      * Sets the value of the 'can_instance' field.
      * @param value The value of 'can_instance'.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder setCanInstance(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.can_instance = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'can_instance' field has been set.
      * @return True if the 'can_instance' field has been set, false otherwise.
      */
    public boolean hasCanInstance() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'can_instance' field.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder clearCanInstance() {
      can_instance = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public long getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder setCreatedAt(long value) {
      validate(fields()[4], value);
      this.created_at = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder clearCreatedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_modified_at' field.
      * @return The value.
      */
    public java.lang.Long getLastModifiedAt() {
      return last_modified_at;
    }


    /**
      * Sets the value of the 'last_modified_at' field.
      * @param value The value of 'last_modified_at'.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder setLastModifiedAt(java.lang.Long value) {
      validate(fields()[5], value);
      this.last_modified_at = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'last_modified_at' field has been set.
      * @return True if the 'last_modified_at' field has been set, false otherwise.
      */
    public boolean hasLastModifiedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'last_modified_at' field.
      * @return This builder.
      */
    public postgres_data_collection_configuration.can_activity.Value.Builder clearLastModifiedAt() {
      last_modified_at = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Value build() {
      try {
        Value record = new Value();
        record.legacy_device_serial_number = fieldSetFlags()[0] ? this.legacy_device_serial_number : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.asset_id = fieldSetFlags()[1] ? this.asset_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.can_activity_state = fieldSetFlags()[2] ? this.can_activity_state : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.can_instance = fieldSetFlags()[3] ? this.can_instance : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.created_at = fieldSetFlags()[4] ? this.created_at : (java.lang.Long) defaultValue(fields()[4]);
        record.last_modified_at = fieldSetFlags()[5] ? this.last_modified_at : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Value>
    WRITER$ = (org.apache.avro.io.DatumWriter<Value>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Value>
    READER$ = (org.apache.avro.io.DatumReader<Value>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.legacy_device_serial_number);

    out.writeString(this.asset_id);

    out.writeString(this.can_activity_state);

    out.writeString(this.can_instance);

    out.writeLong(this.created_at);

    if (this.last_modified_at == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.last_modified_at);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.legacy_device_serial_number = in.readString(this.legacy_device_serial_number instanceof Utf8 ? (Utf8)this.legacy_device_serial_number : null);

      this.asset_id = in.readString(this.asset_id instanceof Utf8 ? (Utf8)this.asset_id : null);

      this.can_activity_state = in.readString(this.can_activity_state instanceof Utf8 ? (Utf8)this.can_activity_state : null);

      this.can_instance = in.readString(this.can_instance instanceof Utf8 ? (Utf8)this.can_instance : null);

      this.created_at = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.last_modified_at = null;
      } else {
        this.last_modified_at = in.readLong();
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.legacy_device_serial_number = in.readString(this.legacy_device_serial_number instanceof Utf8 ? (Utf8)this.legacy_device_serial_number : null);
          break;

        case 1:
          this.asset_id = in.readString(this.asset_id instanceof Utf8 ? (Utf8)this.asset_id : null);
          break;

        case 2:
          this.can_activity_state = in.readString(this.can_activity_state instanceof Utf8 ? (Utf8)this.can_activity_state : null);
          break;

        case 3:
          this.can_instance = in.readString(this.can_instance instanceof Utf8 ? (Utf8)this.can_instance : null);
          break;

        case 4:
          this.created_at = in.readLong();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.last_modified_at = null;
          } else {
            this.last_modified_at = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










