/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trackunit.pipeline;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CalculatedCanInstance extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3475441070514904556L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CalculatedCanInstance\",\"namespace\":\"com.trackunit.pipeline\",\"fields\":[{\"name\":\"activity\",\"type\":{\"type\":\"enum\",\"name\":\"CanActivityState\",\"symbols\":[\"NO_ACTIVITY_DETECTED\",\"ACTIVITY_DETECTED\",\"UNKNOWN\"],\"default\":\"UNKNOWN\"},\"doc\":\"Mandatory field representing the detected activity state\",\"default\":\"UNKNOWN\"},{\"name\":\"updatedAt\",\"type\":\"long\",\"default\":0,\"comment\":\"Time of record being updated\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CalculatedCanInstance> ENCODER =
      new BinaryMessageEncoder<CalculatedCanInstance>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CalculatedCanInstance> DECODER =
      new BinaryMessageDecoder<CalculatedCanInstance>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CalculatedCanInstance> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CalculatedCanInstance> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CalculatedCanInstance> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CalculatedCanInstance>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CalculatedCanInstance to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CalculatedCanInstance from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CalculatedCanInstance instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CalculatedCanInstance fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Mandatory field representing the detected activity state */
  @Deprecated public com.trackunit.pipeline.CanActivityState activity;
  @Deprecated public long updatedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CalculatedCanInstance() {}

  /**
   * All-args constructor.
   * @param activity Mandatory field representing the detected activity state
   * @param updatedAt The new value for updatedAt
   */
  public CalculatedCanInstance(com.trackunit.pipeline.CanActivityState activity, java.lang.Long updatedAt) {
    this.activity = activity;
    this.updatedAt = updatedAt;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return activity;
    case 1: return updatedAt;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: activity = (com.trackunit.pipeline.CanActivityState)value$; break;
    case 1: updatedAt = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'activity' field.
   * @return Mandatory field representing the detected activity state
   */
  public com.trackunit.pipeline.CanActivityState getActivity() {
    return activity;
  }


  /**
   * Sets the value of the 'activity' field.
   * Mandatory field representing the detected activity state
   * @param value the value to set.
   */
  public void setActivity(com.trackunit.pipeline.CanActivityState value) {
    this.activity = value;
  }

  /**
   * Gets the value of the 'updatedAt' field.
   * @return The value of the 'updatedAt' field.
   */
  public long getUpdatedAt() {
    return updatedAt;
  }


  /**
   * Sets the value of the 'updatedAt' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(long value) {
    this.updatedAt = value;
  }

  /**
   * Creates a new CalculatedCanInstance RecordBuilder.
   * @return A new CalculatedCanInstance RecordBuilder
   */
  public static com.trackunit.pipeline.CalculatedCanInstance.Builder newBuilder() {
    return new com.trackunit.pipeline.CalculatedCanInstance.Builder();
  }

  /**
   * Creates a new CalculatedCanInstance RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CalculatedCanInstance RecordBuilder
   */
  public static com.trackunit.pipeline.CalculatedCanInstance.Builder newBuilder(com.trackunit.pipeline.CalculatedCanInstance.Builder other) {
    if (other == null) {
      return new com.trackunit.pipeline.CalculatedCanInstance.Builder();
    } else {
      return new com.trackunit.pipeline.CalculatedCanInstance.Builder(other);
    }
  }

  /**
   * Creates a new CalculatedCanInstance RecordBuilder by copying an existing CalculatedCanInstance instance.
   * @param other The existing instance to copy.
   * @return A new CalculatedCanInstance RecordBuilder
   */
  public static com.trackunit.pipeline.CalculatedCanInstance.Builder newBuilder(com.trackunit.pipeline.CalculatedCanInstance other) {
    if (other == null) {
      return new com.trackunit.pipeline.CalculatedCanInstance.Builder();
    } else {
      return new com.trackunit.pipeline.CalculatedCanInstance.Builder(other);
    }
  }

  /**
   * RecordBuilder for CalculatedCanInstance instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CalculatedCanInstance>
    implements org.apache.avro.data.RecordBuilder<CalculatedCanInstance> {

    /** Mandatory field representing the detected activity state */
    private com.trackunit.pipeline.CanActivityState activity;
    private long updatedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.trackunit.pipeline.CalculatedCanInstance.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.activity)) {
        this.activity = data().deepCopy(fields()[0].schema(), other.activity);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[1].schema(), other.updatedAt);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CalculatedCanInstance instance
     * @param other The existing instance to copy.
     */
    private Builder(com.trackunit.pipeline.CalculatedCanInstance other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.activity)) {
        this.activity = data().deepCopy(fields()[0].schema(), other.activity);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[1].schema(), other.updatedAt);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'activity' field.
      * Mandatory field representing the detected activity state
      * @return The value.
      */
    public com.trackunit.pipeline.CanActivityState getActivity() {
      return activity;
    }


    /**
      * Sets the value of the 'activity' field.
      * Mandatory field representing the detected activity state
      * @param value The value of 'activity'.
      * @return This builder.
      */
    public com.trackunit.pipeline.CalculatedCanInstance.Builder setActivity(com.trackunit.pipeline.CanActivityState value) {
      validate(fields()[0], value);
      this.activity = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'activity' field has been set.
      * Mandatory field representing the detected activity state
      * @return True if the 'activity' field has been set, false otherwise.
      */
    public boolean hasActivity() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'activity' field.
      * Mandatory field representing the detected activity state
      * @return This builder.
      */
    public com.trackunit.pipeline.CalculatedCanInstance.Builder clearActivity() {
      activity = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * @return The value.
      */
    public long getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public com.trackunit.pipeline.CalculatedCanInstance.Builder setUpdatedAt(long value) {
      validate(fields()[1], value);
      this.updatedAt = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * @return This builder.
      */
    public com.trackunit.pipeline.CalculatedCanInstance.Builder clearUpdatedAt() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CalculatedCanInstance build() {
      try {
        CalculatedCanInstance record = new CalculatedCanInstance();
        record.activity = fieldSetFlags()[0] ? this.activity : (com.trackunit.pipeline.CanActivityState) defaultValue(fields()[0]);
        record.updatedAt = fieldSetFlags()[1] ? this.updatedAt : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CalculatedCanInstance>
    WRITER$ = (org.apache.avro.io.DatumWriter<CalculatedCanInstance>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CalculatedCanInstance>
    READER$ = (org.apache.avro.io.DatumReader<CalculatedCanInstance>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.activity.ordinal());

    out.writeLong(this.updatedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.activity = com.trackunit.pipeline.CanActivityState.values()[in.readEnum()];

      this.updatedAt = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.activity = com.trackunit.pipeline.CanActivityState.values()[in.readEnum()];
          break;

        case 1:
          this.updatedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










