/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pluralsight.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AudioCommand extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3212824145503976848L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AudioCommand\",\"namespace\":\"com.pluralsight.avro\",\"fields\":[{\"name\":\"command\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AudioCommand> ENCODER =
      new BinaryMessageEncoder<AudioCommand>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AudioCommand> DECODER =
      new BinaryMessageDecoder<AudioCommand>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AudioCommand> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AudioCommand> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AudioCommand> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AudioCommand>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AudioCommand to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AudioCommand from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AudioCommand instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AudioCommand fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence command;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AudioCommand() {}

  /**
   * All-args constructor.
   * @param command The new value for command
   */
  public AudioCommand(java.lang.CharSequence command) {
    this.command = command;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return command;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: command = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'command' field.
   * @return The value of the 'command' field.
   */
  public java.lang.CharSequence getCommand() {
    return command;
  }


  /**
   * Sets the value of the 'command' field.
   * @param value the value to set.
   */
  public void setCommand(java.lang.CharSequence value) {
    this.command = value;
  }

  /**
   * Creates a new AudioCommand RecordBuilder.
   * @return A new AudioCommand RecordBuilder
   */
  public static com.pluralsight.avro.AudioCommand.Builder newBuilder() {
    return new com.pluralsight.avro.AudioCommand.Builder();
  }

  /**
   * Creates a new AudioCommand RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AudioCommand RecordBuilder
   */
  public static com.pluralsight.avro.AudioCommand.Builder newBuilder(com.pluralsight.avro.AudioCommand.Builder other) {
    if (other == null) {
      return new com.pluralsight.avro.AudioCommand.Builder();
    } else {
      return new com.pluralsight.avro.AudioCommand.Builder(other);
    }
  }

  /**
   * Creates a new AudioCommand RecordBuilder by copying an existing AudioCommand instance.
   * @param other The existing instance to copy.
   * @return A new AudioCommand RecordBuilder
   */
  public static com.pluralsight.avro.AudioCommand.Builder newBuilder(com.pluralsight.avro.AudioCommand other) {
    if (other == null) {
      return new com.pluralsight.avro.AudioCommand.Builder();
    } else {
      return new com.pluralsight.avro.AudioCommand.Builder(other);
    }
  }

  /**
   * RecordBuilder for AudioCommand instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AudioCommand>
    implements org.apache.avro.data.RecordBuilder<AudioCommand> {

    private java.lang.CharSequence command;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pluralsight.avro.AudioCommand.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.command)) {
        this.command = data().deepCopy(fields()[0].schema(), other.command);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AudioCommand instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pluralsight.avro.AudioCommand other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.command)) {
        this.command = data().deepCopy(fields()[0].schema(), other.command);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'command' field.
      * @return The value.
      */
    public java.lang.CharSequence getCommand() {
      return command;
    }


    /**
      * Sets the value of the 'command' field.
      * @param value The value of 'command'.
      * @return This builder.
      */
    public com.pluralsight.avro.AudioCommand.Builder setCommand(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.command = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'command' field has been set.
      * @return True if the 'command' field has been set, false otherwise.
      */
    public boolean hasCommand() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'command' field.
      * @return This builder.
      */
    public com.pluralsight.avro.AudioCommand.Builder clearCommand() {
      command = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AudioCommand build() {
      try {
        AudioCommand record = new AudioCommand();
        record.command = fieldSetFlags()[0] ? this.command : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AudioCommand>
    WRITER$ = (org.apache.avro.io.DatumWriter<AudioCommand>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AudioCommand>
    READER$ = (org.apache.avro.io.DatumReader<AudioCommand>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.command);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.command = in.readString(this.command instanceof Utf8 ? (Utf8)this.command : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.command = in.readString(this.command instanceof Utf8 ? (Utf8)this.command : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










