/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trackunit.pipeline.metadata;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AssetCanInstance extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4622857278533447105L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AssetCanInstance\",\"namespace\":\"com.trackunit.pipeline.metadata\",\"fields\":[{\"name\":\"assetId\",\"type\":\"string\",\"logicalType\":\"UUID\"},{\"name\":\"canInstance\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AssetCanInstance> ENCODER =
      new BinaryMessageEncoder<AssetCanInstance>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AssetCanInstance> DECODER =
      new BinaryMessageDecoder<AssetCanInstance>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AssetCanInstance> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AssetCanInstance> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AssetCanInstance> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AssetCanInstance>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AssetCanInstance to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AssetCanInstance from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AssetCanInstance instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AssetCanInstance fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence assetId;
  @Deprecated public java.lang.CharSequence canInstance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AssetCanInstance() {}

  /**
   * All-args constructor.
   * @param assetId The new value for assetId
   * @param canInstance The new value for canInstance
   */
  public AssetCanInstance(java.lang.CharSequence assetId, java.lang.CharSequence canInstance) {
    this.assetId = assetId;
    this.canInstance = canInstance;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return assetId;
    case 1: return canInstance;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: assetId = (java.lang.CharSequence)value$; break;
    case 1: canInstance = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'assetId' field.
   * @return The value of the 'assetId' field.
   */
  public java.lang.CharSequence getAssetId() {
    return assetId;
  }


  /**
   * Sets the value of the 'assetId' field.
   * @param value the value to set.
   */
  public void setAssetId(java.lang.CharSequence value) {
    this.assetId = value;
  }

  /**
   * Gets the value of the 'canInstance' field.
   * @return The value of the 'canInstance' field.
   */
  public java.lang.CharSequence getCanInstance() {
    return canInstance;
  }


  /**
   * Sets the value of the 'canInstance' field.
   * @param value the value to set.
   */
  public void setCanInstance(java.lang.CharSequence value) {
    this.canInstance = value;
  }

  /**
   * Creates a new AssetCanInstance RecordBuilder.
   * @return A new AssetCanInstance RecordBuilder
   */
  public static com.trackunit.pipeline.metadata.AssetCanInstance.Builder newBuilder() {
    return new com.trackunit.pipeline.metadata.AssetCanInstance.Builder();
  }

  /**
   * Creates a new AssetCanInstance RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AssetCanInstance RecordBuilder
   */
  public static com.trackunit.pipeline.metadata.AssetCanInstance.Builder newBuilder(com.trackunit.pipeline.metadata.AssetCanInstance.Builder other) {
    if (other == null) {
      return new com.trackunit.pipeline.metadata.AssetCanInstance.Builder();
    } else {
      return new com.trackunit.pipeline.metadata.AssetCanInstance.Builder(other);
    }
  }

  /**
   * Creates a new AssetCanInstance RecordBuilder by copying an existing AssetCanInstance instance.
   * @param other The existing instance to copy.
   * @return A new AssetCanInstance RecordBuilder
   */
  public static com.trackunit.pipeline.metadata.AssetCanInstance.Builder newBuilder(com.trackunit.pipeline.metadata.AssetCanInstance other) {
    if (other == null) {
      return new com.trackunit.pipeline.metadata.AssetCanInstance.Builder();
    } else {
      return new com.trackunit.pipeline.metadata.AssetCanInstance.Builder(other);
    }
  }

  /**
   * RecordBuilder for AssetCanInstance instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AssetCanInstance>
    implements org.apache.avro.data.RecordBuilder<AssetCanInstance> {

    private java.lang.CharSequence assetId;
    private java.lang.CharSequence canInstance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.trackunit.pipeline.metadata.AssetCanInstance.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.assetId)) {
        this.assetId = data().deepCopy(fields()[0].schema(), other.assetId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.canInstance)) {
        this.canInstance = data().deepCopy(fields()[1].schema(), other.canInstance);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AssetCanInstance instance
     * @param other The existing instance to copy.
     */
    private Builder(com.trackunit.pipeline.metadata.AssetCanInstance other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.assetId)) {
        this.assetId = data().deepCopy(fields()[0].schema(), other.assetId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.canInstance)) {
        this.canInstance = data().deepCopy(fields()[1].schema(), other.canInstance);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'assetId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAssetId() {
      return assetId;
    }


    /**
      * Sets the value of the 'assetId' field.
      * @param value The value of 'assetId'.
      * @return This builder.
      */
    public com.trackunit.pipeline.metadata.AssetCanInstance.Builder setAssetId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.assetId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'assetId' field has been set.
      * @return True if the 'assetId' field has been set, false otherwise.
      */
    public boolean hasAssetId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'assetId' field.
      * @return This builder.
      */
    public com.trackunit.pipeline.metadata.AssetCanInstance.Builder clearAssetId() {
      assetId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'canInstance' field.
      * @return The value.
      */
    public java.lang.CharSequence getCanInstance() {
      return canInstance;
    }


    /**
      * Sets the value of the 'canInstance' field.
      * @param value The value of 'canInstance'.
      * @return This builder.
      */
    public com.trackunit.pipeline.metadata.AssetCanInstance.Builder setCanInstance(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.canInstance = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'canInstance' field has been set.
      * @return True if the 'canInstance' field has been set, false otherwise.
      */
    public boolean hasCanInstance() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'canInstance' field.
      * @return This builder.
      */
    public com.trackunit.pipeline.metadata.AssetCanInstance.Builder clearCanInstance() {
      canInstance = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AssetCanInstance build() {
      try {
        AssetCanInstance record = new AssetCanInstance();
        record.assetId = fieldSetFlags()[0] ? this.assetId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.canInstance = fieldSetFlags()[1] ? this.canInstance : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AssetCanInstance>
    WRITER$ = (org.apache.avro.io.DatumWriter<AssetCanInstance>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AssetCanInstance>
    READER$ = (org.apache.avro.io.DatumReader<AssetCanInstance>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.assetId);

    out.writeString(this.canInstance);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.assetId = in.readString(this.assetId instanceof Utf8 ? (Utf8)this.assetId : null);

      this.canInstance = in.readString(this.canInstance instanceof Utf8 ? (Utf8)this.canInstance : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.assetId = in.readString(this.assetId instanceof Utf8 ? (Utf8)this.assetId : null);
          break;

        case 1:
          this.canInstance = in.readString(this.canInstance instanceof Utf8 ? (Utf8)this.canInstance : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










