/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trackunit.fleet.data.health.avro;
@org.apache.avro.specific.AvroGenerated
public enum FleetDataHealthIssueType implements org.apache.avro.generic.GenericEnumSymbol<FleetDataHealthIssueType> {
  UNKNOWN, OPERATING_HOURS, NO_CAN_DATA_CONFIGURATION, NO_CAN_DATA_WIRING, DIGITAL_KEY_DISABLED, BLUETOOTH_DISABLED, INSTALLATION_VALIDATION_MISSING, LOW_EXTERNAL_POWER, LOW_BATTERY_POWER, LOW_GPS_COVERAGE, LOW_CELLULAR_COVERAGE, FIRMWARE_ERROR, INTERNAL_FLASH_ERROR, EXCEPTION_ERROR, MALICIOUS_REBOOT_TYPE_0_33, TEMPERATURE_SHUTDOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FleetDataHealthIssueType\",\"namespace\":\"com.trackunit.fleet.data.health.avro\",\"symbols\":[\"UNKNOWN\",\"OPERATING_HOURS\",\"NO_CAN_DATA_CONFIGURATION\",\"NO_CAN_DATA_WIRING\",\"DIGITAL_KEY_DISABLED\",\"BLUETOOTH_DISABLED\",\"INSTALLATION_VALIDATION_MISSING\",\"LOW_EXTERNAL_POWER\",\"LOW_BATTERY_POWER\",\"LOW_GPS_COVERAGE\",\"LOW_CELLULAR_COVERAGE\",\"FIRMWARE_ERROR\",\"INTERNAL_FLASH_ERROR\",\"EXCEPTION_ERROR\",\"MALICIOUS_REBOOT_TYPE_0_33\",\"TEMPERATURE_SHUTDOWN\"],\"default\":\"UNKNOWN\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
