/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trackunit.fleet.data.health.avro;
@org.apache.avro.specific.AvroGenerated
public enum FleetDataHealthIssueState implements org.apache.avro.generic.GenericEnumSymbol<FleetDataHealthIssueState> {
  UNKNOWN, OPEN, RESOLVED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FleetDataHealthIssueState\",\"namespace\":\"com.trackunit.fleet.data.health.avro\",\"symbols\":[\"UNKNOWN\",\"OPEN\",\"RESOLVED\"],\"default\":\"UNKNOWN\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
