/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trackunit.fleet.data.health.avro;
@org.apache.avro.specific.AvroGenerated
public enum FleetDataHealthIssueCategory implements org.apache.avro.generic.GenericEnumSymbol<FleetDataHealthIssueCategory> {
  UNKNOWN, INSTALL_AND_CONFIGURATION_HEALTH, OPERATIONAL_DEVICE_CORE_DEFINITION, FUNCTIONAL_DEVICE_CORE_DEFINITION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FleetDataHealthIssueCategory\",\"namespace\":\"com.trackunit.fleet.data.health.avro\",\"symbols\":[\"UNKNOWN\",\"INSTALL_AND_CONFIGURATION_HEALTH\",\"OPERATIONAL_DEVICE_CORE_DEFINITION\",\"FUNCTIONAL_DEVICE_CORE_DEFINITION\"],\"default\":\"UNKNOWN\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
