/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.trackunit.fleet.data.health.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Fleet Data Health Issues for specific asset */
@org.apache.avro.specific.AvroGenerated
public class FleetDataHealthIssues extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2233090421877045467L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FleetDataHealthIssues\",\"namespace\":\"com.trackunit.fleet.data.health.avro\",\"doc\":\"Fleet Data Health Issues for specific asset\",\"fields\":[{\"name\":\"assetId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"issues\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"FleetDataHealthIssue\",\"doc\":\"Fleet Data Health Issue\",\"fields\":[{\"name\":\"issueId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"category\",\"type\":{\"type\":\"enum\",\"name\":\"FleetDataHealthIssueCategory\",\"symbols\":[\"UNKNOWN\",\"INSTALL_AND_CONFIGURATION_HEALTH\",\"OPERATIONAL_DEVICE_CORE_DEFINITION\",\"FUNCTIONAL_DEVICE_CORE_DEFINITION\"],\"default\":\"UNKNOWN\"},\"default\":\"UNKNOWN\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"FleetDataHealthIssueType\",\"symbols\":[\"UNKNOWN\",\"OPERATING_HOURS\",\"NO_CAN_DATA_CONFIGURATION\",\"NO_CAN_DATA_WIRING\",\"DIGITAL_KEY_DISABLED\",\"BLUETOOTH_DISABLED\",\"INSTALLATION_VALIDATION_MISSING\",\"LOW_EXTERNAL_POWER\",\"LOW_BATTERY_POWER\",\"LOW_GPS_COVERAGE\",\"LOW_CELLULAR_COVERAGE\",\"FIRMWARE_ERROR\",\"INTERNAL_FLASH_ERROR\",\"EXCEPTION_ERROR\",\"MALICIOUS_REBOOT_TYPE_0_33\",\"TEMPERATURE_SHUTDOWN\"],\"default\":\"UNKNOWN\"},\"default\":\"UNKNOWN\"}]}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FleetDataHealthIssues> ENCODER =
      new BinaryMessageEncoder<FleetDataHealthIssues>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FleetDataHealthIssues> DECODER =
      new BinaryMessageDecoder<FleetDataHealthIssues>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FleetDataHealthIssues> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FleetDataHealthIssues> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FleetDataHealthIssues> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FleetDataHealthIssues>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FleetDataHealthIssues to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FleetDataHealthIssues from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FleetDataHealthIssues instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FleetDataHealthIssues fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence assetId;
  @Deprecated public java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue> issues;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FleetDataHealthIssues() {}

  /**
   * All-args constructor.
   * @param assetId The new value for assetId
   * @param issues The new value for issues
   */
  public FleetDataHealthIssues(java.lang.CharSequence assetId, java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue> issues) {
    this.assetId = assetId;
    this.issues = issues;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return assetId;
    case 1: return issues;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: assetId = (java.lang.CharSequence)value$; break;
    case 1: issues = (java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'assetId' field.
   * @return The value of the 'assetId' field.
   */
  public java.lang.CharSequence getAssetId() {
    return assetId;
  }


  /**
   * Sets the value of the 'assetId' field.
   * @param value the value to set.
   */
  public void setAssetId(java.lang.CharSequence value) {
    this.assetId = value;
  }

  /**
   * Gets the value of the 'issues' field.
   * @return The value of the 'issues' field.
   */
  public java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue> getIssues() {
    return issues;
  }


  /**
   * Sets the value of the 'issues' field.
   * @param value the value to set.
   */
  public void setIssues(java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue> value) {
    this.issues = value;
  }

  /**
   * Creates a new FleetDataHealthIssues RecordBuilder.
   * @return A new FleetDataHealthIssues RecordBuilder
   */
  public static com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder newBuilder() {
    return new com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder();
  }

  /**
   * Creates a new FleetDataHealthIssues RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FleetDataHealthIssues RecordBuilder
   */
  public static com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder newBuilder(com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder other) {
    if (other == null) {
      return new com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder();
    } else {
      return new com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder(other);
    }
  }

  /**
   * Creates a new FleetDataHealthIssues RecordBuilder by copying an existing FleetDataHealthIssues instance.
   * @param other The existing instance to copy.
   * @return A new FleetDataHealthIssues RecordBuilder
   */
  public static com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder newBuilder(com.trackunit.fleet.data.health.avro.FleetDataHealthIssues other) {
    if (other == null) {
      return new com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder();
    } else {
      return new com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder(other);
    }
  }

  /**
   * RecordBuilder for FleetDataHealthIssues instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FleetDataHealthIssues>
    implements org.apache.avro.data.RecordBuilder<FleetDataHealthIssues> {

    private java.lang.CharSequence assetId;
    private java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue> issues;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.assetId)) {
        this.assetId = data().deepCopy(fields()[0].schema(), other.assetId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.issues)) {
        this.issues = data().deepCopy(fields()[1].schema(), other.issues);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing FleetDataHealthIssues instance
     * @param other The existing instance to copy.
     */
    private Builder(com.trackunit.fleet.data.health.avro.FleetDataHealthIssues other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.assetId)) {
        this.assetId = data().deepCopy(fields()[0].schema(), other.assetId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.issues)) {
        this.issues = data().deepCopy(fields()[1].schema(), other.issues);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'assetId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAssetId() {
      return assetId;
    }


    /**
      * Sets the value of the 'assetId' field.
      * @param value The value of 'assetId'.
      * @return This builder.
      */
    public com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder setAssetId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.assetId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'assetId' field has been set.
      * @return True if the 'assetId' field has been set, false otherwise.
      */
    public boolean hasAssetId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'assetId' field.
      * @return This builder.
      */
    public com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder clearAssetId() {
      assetId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'issues' field.
      * @return The value.
      */
    public java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue> getIssues() {
      return issues;
    }


    /**
      * Sets the value of the 'issues' field.
      * @param value The value of 'issues'.
      * @return This builder.
      */
    public com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder setIssues(java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue> value) {
      validate(fields()[1], value);
      this.issues = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'issues' field has been set.
      * @return True if the 'issues' field has been set, false otherwise.
      */
    public boolean hasIssues() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'issues' field.
      * @return This builder.
      */
    public com.trackunit.fleet.data.health.avro.FleetDataHealthIssues.Builder clearIssues() {
      issues = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FleetDataHealthIssues build() {
      try {
        FleetDataHealthIssues record = new FleetDataHealthIssues();
        record.assetId = fieldSetFlags()[0] ? this.assetId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.issues = fieldSetFlags()[1] ? this.issues : (java.util.List<com.trackunit.fleet.data.health.avro.FleetDataHealthIssue>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FleetDataHealthIssues>
    WRITER$ = (org.apache.avro.io.DatumWriter<FleetDataHealthIssues>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FleetDataHealthIssues>
    READER$ = (org.apache.avro.io.DatumReader<FleetDataHealthIssues>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










